export interface City 
    {city: string}


export const Cities:City[] = [
{city: "Select city"},
{city: "Arauca"},
                { city:"Armenia"},
                { city:"Barranquilla"},
                { city:"Bogotá"},
                { city:"Bucaramanga"},
                { city:"Cali"},
                { city:"Cartagena"},
                { city:"Cúcuta"},
                { city:"Florencia"},
                { city:"Ibagué"},
                { city:"Leticia"},
                { city:"Manizales"},
                { city:"Medellín"},
                { city:"Mitú"},
                { city:"Mocoa"},
                { city:"Montería"},
                { city:"Neiva"},
                { city:"Pasto"},
                { city:"Pereira"},
                { city:"Popayán"},
                { city:"Puerto Carreño"},
                { city:"Puerto Inírida"},
                { city:"Quibdó"},
                { city:"Riohacha"},
                { city:"San Andrés"},
                { city:"San José del Guaviare"},
                { city:"Santa Marta"},
                { city:"Sincelejo"},
                { city:"Tunja"},
                { city:"Valledupar"},
                { city:"Villavicencio"},
                { city:"Yopal"},
]

export const Departments = [
                {Department:"Antioquia"},
                {Department:"Arauca"},
                {Department:"Atlántico"},
                {Department:"Bolívar"},
                {Department:"Boyacá"},
		        {Department:"Caldas"},
                {Department:"Caquetá"},
                {Department:"Casanare"},
                {Department:"Cauca"},
                {Department:"Cesar"},
                {Department:"Chocó"},
                {Department:"Córdoba"},
                {Department:"Cundinamarca"},
                {Department:"Guainía"},
		        {Department:"Guaviare"},
                {Department:"Huila"},
                {Department:"La Guajira"},
                {Department:"Magdalena"},
		        {Department:"Meta"},
                {Department:"Nariño"},
                {Department:"Norte de Santander"},
                {Department:"Putumayo"},
                {Department:"Quindío"},
		        {Department:"Risaralda"},
                {Department:"San Andrés y Providencia"},
                {Department:"Santander"},
                {Department:"Sucre"},
                {Department:"Tolima"},
                {Department:"Valle del Cauca"},
                {Department:"Vaupés"},
                {Department:"Vichada"},
]